Remove superfluous argument
It caused errors of the form:
pyth/pyth/plugins/rtf15/reader.py", line 434, in handle
    handler()
TypeError: handle_super() takes exactly 2 arguments (1 given)

This happened both in python2 and python3